### ISSUE TITLE
Implement vee-validate, use a centralized object to define fields contents

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#3]
Issues to be done upfront: #239

Network type must be defaulted

3.Prevent transactions from being sent in network types that do not match (networkType in senderAccount, receiverAccount and node)

**Comment by decentraliser** [comment]
#256

**Comment by decentraliser** [comment]
CryptoBeliever Yesterday at 10:11 PM
Issue: Transfer form - amount field should support comma as separator
Expected Behaviour:
Amount field should allow provide comma as a decimal separator.
Actual Behaviour:
When comma separator is used error "The Amount field must be 0 or more"
Environment:
- Connected API node: http://api-01.mt.ap-northeast-1.nemtech.network:3000
- Wallet version: v0.8.5


https://files.slack.com/files-tmb/T9EAN12HX-FQ3JLG94G-1fa9f66bd2/image_720.png
